version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devsecops-poc"

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo "Installing Security Tools"

      # Upgrade pip
      - python3 -m pip install --upgrade pip

      # Semgrep
      - pip3 install semgrep
      - semgrep --version

      # Checkov
      - pip3 install checkov
      - checkov --version

      # Trivy
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - ./bin/trivy --version

      # Gitleaks
      - GITLEAKS_VERSION=8.24.2
      - wget https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
      - tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
      - chmod +x gitleaks
      - mv gitleaks /usr/local/bin/
      - gitleaks version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"

      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}

      - export IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}

      - echo "IMAGE_URI=${IMAGE_URI}"

  build:
    commands:
      - echo "========== GITLEAKS =========="
      - gitleaks detect --source . --no-git || true

      - echo "========== SEMGREP =========="
      - semgrep scan --config auto . || true

      - echo "========== CHECKOV =========="
      - checkov -d Terraform --soft-fail

      - echo "========== TRIVY FILESYSTEM SCAN =========="
      - ./bin/trivy fs . --severity HIGH,CRITICAL --exit-code 0

      - echo "========== DOCKER BUILD =========="
      - docker build -t ${IMAGE_URI} ./app

      - echo "========== TRIVY IMAGE SCAN =========="
      - ./bin/trivy image --severity HIGH,CRITICAL --exit-code 0 ${IMAGE_URI}

  post_build:
    commands:
      - echo "========== PUSH IMAGE =========="
      - docker push ${IMAGE_URI}

      - echo "========== CREATE IMAGEDEFINITIONS =========="
      - printf '[{"name":"devsecops-app","imageUri":"%s"}]' ${IMAGE_URI} > imagedefinitions.json

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
