version: 0.2

env:
variables:
IMAGE_REPO_NAME: "devsecops-poc"

phases:
install:
runtime-versions:
nodejs: 18
commands:
- echo "BUILD SPEC VERSION 4"
- terraform version || true
- pip3 install checkov

pre_build:
commands:
- echo "Pre-build phase"

build:
commands:
- echo "Build phase"

post_build:
commands:
- echo "Post-build phase"

artifacts:
files:
- "**/*"
