version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devsecops-poc"
    ARTIFACT_BUCKET: "devsecops-artifacts-dev"

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo "Installing Security Tools"
      - python3 -m pip install --upgrade pip -q
      - pip3 install -q semgrep checkov

      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh > /dev/null 2>&1

      - GITLEAKS_VERSION=8.24.2
      - wget -q https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
      - tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
      - chmod +x gitleaks
      - mv gitleaks /usr/local/bin/

      - echo "Tool Versions"
      - semgrep --version
      - checkov --version
      - ./bin/trivy --version
      - gitleaks version

  pre_build:
    commands:
      - echo "Preparing Build"

      - mkdir -p reports

      - export BUILD_ID=${CODEBUILD_BUILD_NUMBER}
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}

      - export IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}

      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo "IMAGE_URI=${IMAGE_URI}"

  build:
    commands:
      - echo "Running Security Scans"

      - gitleaks detect --source . --no-git --report-format json --report-path reports/gitleaks.json || true

      - semgrep scan --config auto --quiet --json --output reports/semgrep.json || true

      - checkov -d Terraform --quiet -o json --soft-fail > reports/checkov.json || true

      - ./bin/trivy fs . --scanners vuln --quiet --severity HIGH,CRITICAL --format json -o reports/trivy-fs.json

      - echo "Building Docker Image"
      - docker build -t ${IMAGE_URI} ./app

      - ./bin/trivy image ${IMAGE_URI} --scanners vuln --quiet --severity HIGH,CRITICAL --format json -o reports/trivy-image.json

      - echo "Generated Reports"
      - find reports -type f

      - echo "Generating Dashboard"
      - test -f cicd/dashboard.py && python3 cicd/dashboard.py || echo "Dashboard script not found"

  post_build:
    commands:
      - echo "Uploading Reports"

      - aws s3 cp reports/ s3://${ARTIFACT_BUCKET}/security-dashboard/build-${BUILD_ID}/ --recursive

      - echo "Pushing Docker Image"
      - docker push ${IMAGE_URI}

      - echo "Creating ECS Artifact"

      - printf '[{"name":"devsecops-app","imageUri":"%s"}]' ${IMAGE_URI} > imagedefinitions.json

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
